pipeline {
      agent { node { label 'Agent-1' } }
      options{
            ansiColor('xterm')
      }

      stages {
            stage('Init') {
                  steps {
                        sh'''
                              cd 01-VPC
                              terraform init
                              
                              

                         '''
                  }
            }
            stage('Plan') {
                  steps {
                          sh'''
                              cd 01-VPC 
                              ls -ltr
                              pwd
                              terraform plan

                         '''
                  }
            }

             stage('Approve') {
                  steps {
                         input "Shall I apply?"
                  }
            }

             stage('Apply') {
                  steps {
                         sh 'cd 01-VPC'
                         sh 'terraform apply -auto-approve'
                  }
            }
      }

      post {
            always {
                  echo 'I will always run whether job is success or not!'
            }
            success {
                  echo 'I will run only when job is success'
            }
            failure {
                  echo 'I will run only when job is fail'
            }
      }
}

